cache::alternate_domains:
  ores.beta.wmflabs.org:
    caching: pass
cache::app_def_be_opts:
  between_bytes_timeout: 31s
  connect_timeout: 3s
  first_byte_timeout: 63s
  max_connections: 1000
  port: 80
cache::cluster: text
cache::nodes:
  text:
    eqiad:
    - localhost
cache::text::nodes:
  eqiad:
  - localhost
cluster: cache_text
kafka_clusters:
  analytics-traffic:
    brokers:
      deployment-kafka01.deployment-prep.eqiad.wmflabs:
        id: 1
      deployment-kafka03.deployment-prep.eqiad.wmflabs:
        id: 2
    ipv6: false
    zookeeper_cluster_name: main-deployment-prep
  main-deployment-prep:
    brokers:
      deployment-kafka04.deployment-prep.eqiad.wmflabs:
        id: 4
      deployment-kafka05.deployment-prep.eqiad.wmflabs:
        id: 5
    ipv6: false
    zookeeper_cluster_name: main-deployment-prep
profile::cache::haproxykafka::ensure: absent
profile::cache::haproxykafka::kafka:
  batch_deadline: 1000ms
  batch_size: 102400
  dlq_topic: webrequest_errors
  flush_timeout: 1000
  rdkafka:
    acks: all
    batch.num.messages: 9000
    client.id: '%{facts.hostname}'
    compression.codec: snappy
    queue.buffering.max.messages: 720000
    queue.buffering.max.ms: 1000
    security.protocol: SSL
    ssl.ca.location: /etc/ssl/certs/wmf-ca-certificates.crt
    ssl.cipher.suites: ECDHE-ECDSA-AES256-GCM-SHA384
    ssl.curves.list: P-256
    ssl.sigalgs.list: ECDSA+SHA256
    topic.request.required.acks: 1
  topic: webrequest_undefined
profile::cache::haproxykafka::kafka_cluster_name: main-deployment-prep
profile::cache::haproxykafka::logparser:
  batch_deadline: 1000ms
  batch_size: 102400
profile::cache::haproxykafka::message_buffer: 1000000.0
profile::cache::haproxykafka::monitoring:
  enable_pprof: true
  enable_prometheus: true
  prometheus_parsing_buckets:
  - 5.0e-06
  - 1.0e-05
  - 5.0e-05
  - 0.0001
  - 0.0005
  - 0.001
  - 0.005
  prometheus_prefix: haproxykafka_
  prometheus_processing_buckets:
  - 1.0e-06
  - 5.0e-06
  - 1.0e-05
  - 2.0e-05
  - 3.0e-05
  - 5.0e-05
  - 0.0001
  - 0.0005
  - 0.001
  server_bind: :9341
profile::cache::haproxykafka::sdid: haproxykafka@0
profile::cache::haproxykafka::socket:
  batch_deadline: 1000ms
  batch_size: 102400
  group: haproxykafka
  mode: '0622'
  path: /var/run/haproxykafka/haproxykafka.sock
  user: haproxykafka
profile::cache::haproxykafka::transform_rules:
  date_format: '2006-01-02T15:04:05Z'
  date_tz: UTC
  haproxy_format: 02/Jan/2006:15:04:05.000
profile::cache::haproxykafka::workers: 2
profile::cache::kafka::eventlogging::kafka_cluster_name: jumbo-eqiad
profile::cache::kafka::statsv::kafka_cluster_name: jumbo-eqiad
profile::cache::purge::backend_addr: 127.0.0.1:3128
profile::cache::purge::frontend_addr: /run/varnish-privileged.socket
profile::cache::purge::use_pki: true
profile::cache::ssl::wikibase::acme_chief: false
profile::cache::ssl::wikibase::le_subjects:
- whatever.org
profile::cache::varnish::frontend::fe_vcl_config:
  admission_policy: exp
  allowed_methods: ^(GET|HEAD|OPTIONS|PATCH|POST|PURGE|PUT|DELETE)$
  exp_policy_base: -20.3
  exp_policy_rate: 0.1
  keep: 1d
  large_objects_cutoff: 262144
  maps_domain: maps.beta.wmflabs.org
  measure_domain_regex: ^measure-(eqiad|codfw|esams|ulsfo|eqsin|drmrs)\.wikimedia\.org$
  public_clouds_shutdown: false
  purge_host_regex: ^(?!(upload|upload\.wikimedia|maps)\.beta\.wmflabs\.org)
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.wikimedia.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
  varnish_probe_ms: 100
profile::cache::varnish::frontend::separate_vcl:
- misc
profile::puppetserver::volatile::geoip_fetch_private: false
profile::trafficserver::backend::default_lua_scripts:
- set-x-cache
profile::trafficserver::backend::monitor_enable: false
profile::trafficserver::backend::outbound_tls_settings:
  cacert_dirpath: /etc/ssl/certs
  cacert_filename: Puppet_Internal_CA.pem
  common:
    cipher_suite: -ALL:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
    enable_tlsv1: 0
    enable_tlsv1_1: 0
    enable_tlsv1_2: 1
    enable_tlsv1_3: 0
  verify_origin: true
  verify_server_policy: ENFORCED
prometheus::varnishkafka_exporter::config:
  num_entries_to_get: 2
  required_entries:
  - kafka
  - varnishkafka
  stats_files:
  - /var/cache/varnishkafka/webrequest.stats.json
zookeeper_clusters:
  main-deployment-prep:
    hosts:
      deployment-zookeeper02.eqiad.wmflabs: '2'
