cluster: parsoid
has_lvs: false
profile::envoy::ensure: absent
profile::mediawiki::apc_shm_size: 128M
profile::mediawiki::httpd::logrotate_retention: 12
profile::mediawiki::mcrouter_wancache::num_proxies: 5
profile::mediawiki::php::enable_fpm: true
profile::mediawiki::php::fpm_config:
  apc.ttl: 10
  opcache.interned_strings_buffer: 96
  opcache.memory_consumption: 1024
profile::mediawiki::php::php_version: '7.2'
profile::mediawiki::php::request_timeout: 201
profile::mediawiki::php::restarts::ensure: present
profile::mediawiki::php::restarts::has_lvs: false
profile::mediawiki::php::restarts::opcache_limit: 200
profile::mediawiki::vhost_feature_flags: {}
profile::mediawiki::webserver::has_tls: false
