cache::app_def_be_opts:
  between_bytes_timeout: 60s
  connect_timeout: 5s
  first_byte_timeout: 35s
  max_connections: 10000
  port: 80
cache::app_directors:
  swift:
    backends:
      eqiad: deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  swift_thumbs:
    backends:
      eqiad: deployment-ms-fe03.deployment-prep.eqiad.wmflabs
cache::nodes:
  upload:
    eqiad_ats:
    - deployment-cache-upload06.deployment-prep.eqiad.wmflabs
cache::req_handling:
  default:
    director: swift
    subpaths:
      ^/+[^/]+/[^/]+/thumb/:
        director: swift_thumbs
profile::cache::ssl::unified::acme_chief: true
profile::cache::varnish::backend::be_extra_vcl:
- upload-common
- normalize_path
profile::cache::varnish::backend::be_vcl_config:
  pass_random: true
profile::cache::varnish::frontend::fe_extra_vcl:
- normalize_path
profile::cache::varnish::frontend::fe_vcl_config:
  admission_policy: none
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  enable_geoiplookup: true
  keep: 1d
  maps_domain: maps.beta.wmflabs.org
  pass_random: false
  purge_host_regex: ^(upload|maps)\.beta\.wmflabs\.org$
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
  varnish_probe_ms: 100
profile::trafficserver::backend::mapping_rules:
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="2F"'
  - '@pparam="21 24 26 27 28 29 2A 2B 2C 3A 3B 3D 40 5B 5D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/x-mediawiki-original.lua'
  replacement: http://deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  target: http://upload.beta.wmflabs.org
  type: map
profile::trafficserver::tls::inbound_tls_settings:
  common:
    cipher_suite: -ALL:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA
    enable_tlsv1: 0
    enable_tlsv1_1: 0
    enable_tlsv1_2: 1
    enable_tlsv1_3: 0
  dhparams_file: /etc/ssl/dhparam.pem
  do_ocsp: 0
  load_elevated: 1
  max_record_size: 16383
  prioritize_chacha: 1
  session_cache: 2
  session_cache_auto_clear: 1
  session_cache_buckets: 256
  session_cache_size: 102400
  session_ticket_enable: 0
  ssl_handshake_timeout_in: 60
varnish_version4: true
