profile::mediawiki::jobrunner::default_php_version: '8.1'
profile::mediawiki::php::absented_php_versions:
- '7.4'
profile::mediawiki::php::php_versions:
- '8.1'
profile::mediawiki::webserver::default_php_version: '8.1'
