cache::app_def_be_opts:
  between_bytes_timeout: 60s
  connect_timeout: 5s
  first_byte_timeout: 35s
  max_connections: 10000
  port: 80
cache::app_directors:
  swift:
    backends:
      eqiad: deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  swift_thumbs:
    backends:
      eqiad: deployment-ms-fe03.deployment-prep.eqiad.wmflabs
cache::req_handling:
  default:
    director: swift
    subpaths:
      ^/+[^/]+/[^/]+/thumb/:
        director: swift_thumbs
profile::cache::ssl::unified::acme_chief: true
profile::cache::varnish::backend::be_extra_vcl:
- upload-common
- normalize_path
profile::cache::varnish::backend::be_vcl_config:
  pass_random: true
profile::cache::varnish::frontend::fe_extra_vcl:
- upload-common
- normalize_path
profile::cache::varnish::frontend::fe_vcl_config:
  admission_policy: none
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  enable_geoiplookup: true
  keep: 1d
  maps_domain: maps.beta.wmflabs.org
  pass_random: false
  purge_host_regex: ^(upload|maps)\.beta\.wmflabs\.org$
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
  varnish_probe_ms: 100
varnish_version4: true
