profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 20.10.5+dfsg1-1
profile::docker::runner::service_defs:
  function-evaluator-js-wasm:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 4
      services:
      - conf:
          port: 6938
        module: ./app.js
        name: function-evaluator-js-wasm
      worker_heap_limit_mb: 1000
    environment:
      ASPIRATIONAL_WASM_BINARY: /srv/service/programming-languages/wasmedge_quickjs.so
      ENABLE_WASMEDGE_LIMITS: 0
      EXECUTOR_PROCESS_POOL_SIZE: 5
      FUNCTION_EVALUATOR_TIMEOUT_MS: 20000
      WASMEDGE_GAS_LIMIT: 1000000
      WASMEDGE_MEMORY_PAGE_LIMIT: 1000000
      WASMEDGE_TIMEOUT_MS: 21000
      WASM_BINARY: /srv/service/programming-languages/wasmedge_quickjs_uncompiled.wasm
    image_name: wasm-javascript-all
    namespace: repos/abstract-wiki/wikifunctions/function-evaluator
    override_cmd: -c /etc/function-evaluator-js-wasm/config.yaml
    port: 6938
    runtime: runsc
    version: latest
  function-evaluator-py-wasm:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 4
      services:
      - conf:
          port: 6939
        module: ./app.js
        name: function-evaluator-py-wasm
      worker_heap_limit_mb: 1000
    environment:
      ASPIRATIONAL_WASM_BINARY: /srv/service/programming-languages/rustpython.so
      ENABLE_WASMEDGE_LIMITS: 0
      EXECUTOR_PROCESS_POOL_SIZE: 5
      FUNCTION_EVALUATOR_TIMEOUT_MS: 20000
      WASMEDGE_GAS_LIMIT: 1000000
      WASMEDGE_MEMORY_PAGE_LIMIT: 1000000
      WASMEDGE_TIMEOUT_MS: 21000
      WASM_BINARY: /srv/service/programming-languages/rustpython_uncompiled.wasm
    image_name: wasm-python3-all
    namespace: repos/abstract-wiki/wikifunctions/function-evaluator
    override_cmd: -c /etc/function-evaluator-py-wasm/config.yaml
    port: 6939
    runtime: runsc
    version: latest
  mediawiki-services-function-orchestrator:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 7
      services:
      - conf:
          cors: '*'
          mwapi_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              user-agent: '{{user-agent}}'
            method: post
            uri: https://{{domain}}/w/api.php
          port: 6254
          restbase_req:
            body: '{{request.body}}'
            headers: '{{request.headers}}'
            method: '{{request.method}}'
            query: '{{ default(request.query, {}) }}'
            uri: https://{{domain}}/api/rest_v1/{+path}
          spec: ./spec.yaml
        module: ./app.js
        name: function-orchestrator
      worker_heap_limit_mb: 500
    environment:
      FUNCTION_EVALUATOR_TIMEOUT_MS: '9000'
      FUNCTION_ORCHESTRATOR_RATE_LIMIT_TTL_SECONDS: '180'
      JS_EVAL_URI_SHOULD_WORK_BUT_DOESNT: https://wikifunctions-evaluator-javascript-beta.wmcloud.org/1/v1/evaluate/
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
      ORCHESTRATOR_CONFIG: '{ "addNestedMetadata": true, "evaluatorConfigs": [ { "programmingLanguages":
        ["Z610","Z611","Z612","Z613","Z614","Z615"], "evaluatorUri": "http://172.16.1.154:6939/1/v1/evaluate/",
        "evaluatorWs": "", "useReentrance": false, "allowCustomDerializers": true
        }, { "programmingLanguages": ["Z600", "Z601", "Z602", "Z603", "Z604", "Z605",
        "Z606", "Z607", "Z608"], "evaluatorUri": "http://172.16.1.154:6938/1/v1/evaluate/",
        "evaluatorWs": "", "useReentrance": false, "allowCustomDerializers": true
        } ] }'
      ORCHESTRATOR_TIMEOUT_MS: '15000'
      PROGRAMMING_LANGUAGE_DIR: /srv/service/programming-languages
      PY_EVAL_URI_SHOULD_WORK_BUT_DOESNT: https://wikifunctions-evaluator-python3-beta.wmcloud.org/1/v1/evaluate/
      WASMEDGE_HOME: /srv/service/programming-languages/wasmedge
      WIKI_API_URL: https://wikifunctions.beta.wmflabs.org/w/api.php
    image_name: function-orchestrator
    namespace: repos/abstract-wiki/wikifunctions
    override_cmd: -c /etc/mediawiki-services-function-orchestrator/config.yaml
    port: 6254
    version: latest
profile::docker::storage::physical_volumes: /dev/md1
profile::docker::storage::vg_to_remove: todelete
