lookup_options:
  profile::opensearch::common_settings:
    merge:
      strategy: first
profile::opensearch::base_data_dir: /srv/opensearch
profile::opensearch::cirrus::enable_remote_search: true
profile::opensearch::cirrus::ssl_provider: cfssl
profile::opensearch::common_settings:
  plugins_mandatory:
  - analysis-hebrew
  - analysis-icu
  - analysis-smartcn
  - analysis-stempel
  - analysis-ukrainian
  - cirrus-highlighter
  - opensearch-analysis-stconvert
  - opensearch-extra
  - opensearch-extra-analysis-esperanto
  - opensearch-extra-analysis-serbian
  - opensearch-extra-analysis-slovak
  - opensearch-ltr
  - repository-s3
profile::opensearch::config_version: '2'
profile::opensearch::java_home: /usr/lib/jvm/java-21-openjdk-amd64
profile::opensearch::version: 2.19.5
puppetmaster: deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
puppetserver: deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
