service::catalog:
  restbase:
    description: Restbase dummy service config
    encryption: true
    ip:
      eqiad:
        default: 172.16.3.186
    page: false
    port: 7231
    sites:
    - eqiad
    state: production
