cache::alternate_domains: {}
cache::app_def_be_opts:
  between_bytes_timeout: 60s
  connect_timeout: 5s
  first_byte_timeout: 35s
  max_connections: 10000
  port: 80
cache::app_directors:
  swift:
    backends:
      eqiad: deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  swift_thumbs:
    backends:
      eqiad: deployment-ms-fe03.deployment-prep.eqiad.wmflabs
cache::cluster: upload
cache::lua_support: true
cache::nodes:
  upload:
    eqiad:
    - deployment-cache-upload06.deployment-prep.eqiad.wmflabs
cache::req_handling:
  default:
    caching: normal
cache::upload::nodes:
  eqiad:
  - deployment-cache-upload06.deployment-prep.eqiad.wmflabs
profile::cache::base::varnish_version: 5
profile::cache::ssl::unified::acme_chief: true
profile::cache::ssl::unified::certs: []
profile::cache::ssl::unified::certs_active: []
profile::cache::ssl::unified::letsencrypt: false
profile::cache::varnish::backend::be_extra_vcl:
- upload-common
- normalize_path
profile::cache::varnish::backend::be_vcl_config:
  pass_random: true
profile::cache::varnish::common_vcl_config:
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  maps_domain: maps.beta.wmflabs.org
  purge_host_regex: ^(?!(upload|upload\.wikimedia|maps)\.beta\.wmflabs\.org)
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.wikimedia.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
profile::cache::varnish::frontend::fe_extra_vcl:
- normalize_path
profile::cache::varnish::frontend::fe_vcl_config:
  admission_policy: none
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  enable_geoiplookup: true
  keep: 1d
  large_objects_cutoff: 262144
  maps_domain: maps.beta.wmflabs.org
  pass_random: false
  purge_host_regex: ^(upload|upload\.wikimedia|maps)\.beta\.wmflabs\.org$
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.wikimedia.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
  varnish_probe_ms: 100
profile::cache::varnish::frontend::packages_component: component/varnish6
profile::trafficserver::backend::mapping_rules:
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="2F"'
  - '@pparam="21 24 26 27 28 29 2A 2B 2C 3A 3B 3D 40 5B 5D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/x-mediawiki-original.lua'
  replacement: http://deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  target: http://upload.beta.wmflabs.org
  type: map
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="2F"'
  - '@pparam="21 24 26 27 28 29 2A 2B 2C 3A 3B 3D 40 5B 5D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/x-mediawiki-original.lua'
  replacement: http://deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  target: http://upload.wikimedia.beta.wmflabs.org
  type: map
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
