profile::cassandra::instances:
  deployment-sessionstore01.deployment-prep.eqiad.wmflabs: {}
profile::cassandra::rack: rack1
profile::cassandra::settings:
  cluster_name: sessions-beta
  default_instance_params:
    rpc_address: '%{::ipaddress}'
  listen_address: '%{::ipaddress}'
  logstash_host: deployment-logstash03.deployment-prep.eqiad.wmflabs
  target_version: 3.x
