profile::ores::celery::queue_maxsize: 100
profile::ores::celery::workers: 4
profile::ores::logstash_host: localhost
profile::ores::web::workers: 8
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
