cache::alternate_domains: {}
cache::cluster: upload
cache::lua_support: true
cache::nodes:
  upload:
    eqiad:
    - deployment-cache-upload08.deployment-prep.eqiad1.wikimedia.cloud
cache::req_handling:
  default:
    caching: normal
cache::upload::nodes:
  eqiad:
  - deployment-cache-upload08.deployment-prep.eqiad1.wikimedia.cloud
profile::cache::base::varnish_version: 5
profile::cache::ssl::unified::acme_chief: true
profile::cache::ssl::unified::certs: []
profile::cache::ssl::unified::certs_active: []
profile::cache::ssl::unified::letsencrypt: false
profile::cache::varnish::frontend::fe_extra_vcl:
- normalize_path
profile::cache::varnish::frontend::fe_vcl_config:
  admission_policy: none
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  enable_geoiplookup: true
  keep: 1d
  large_objects_cutoff: 262144
  maps_domain: maps.beta.wmflabs.org
  measure_domain_regex: ^measure-(eqiad|codfw|esams|ulsfo|eqsin|drmrs)\.wikimedia\.org$
  pass_random: false
  purge_host_regex: ^(upload\.wikimedia|maps)\.beta\.wmflabs\.org$
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.wikimedia.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
  varnish_probe_ms: 100
profile::trafficserver::backend::mapping_rules:
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="2F"'
  - '@pparam="21 24 26 27 28 29 2A 2B 2C 3A 3B 3D 40 5B 5D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/x-mediawiki-original.lua'
  replacement: http://deployment-ms-fe04.deployment-prep.eqiad1.wikimedia.cloud
  target: http://upload.wikimedia.beta.wmflabs.org
  type: map
