mtail::logs:
- /var/log/logstash/logstash-json.log
profile::elastalert::ensure: present
profile::elasticsearch::logstash::curator_actions:
  1:
    action: delete_indices
    description: 'deployment-prep: delete older than 5 days'
    filters:
    - exclude: true
      filtertype: pattern
      kind: prefix
      value: ^\..*
    - direction: older
      filtertype: age
      source: creation_date
      unit: days
      unit_count: 3
    options:
      ignore_empty_list: true
  20:
    action: replicas
    description: 'deployment-prep: after 1 day set number of replicas to 1'
    filters:
    - exclude: true
      filtertype: pattern
      kind: prefix
      value: ^\..*
    - direction: older
      filtertype: age
      source: creation_date
      unit: days
    options:
      count: 1
      ignore_empty_list: true
profile::elasticsearch::logstash::jobs_host: deployment-logstash05.deployment-prep.eqiad1.wikimedia.cloud
profile::logstash::apifeatureusage::curator_actions:
  1:
    action: delete_indices
    description: 'apifeatureusage: delete older than 91 days'
    filters:
    - filtertype: pattern
      kind: prefix
      value: apifeatureusage-
    - direction: older
      filtertype: age
      source: name
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 91
    options:
      ignore_empty_list: true
  2:
    action: replicas
    description: 'apifeatureusage: set replicas to 1 after 31 days'
    filters:
    - exclude: null
      filtertype: pattern
      kind: prefix
      value: apifeatureusage-
    - direction: older
      filtertype: age
      source: creation_date
      unit: days
      unit_count: 31
    options:
      count: 1
      ignore_empty_list: true
  5:
    action: forcemerge
    description: forcemerge indexes older than 2 days
    filters:
    - exclude: null
      filtertype: pattern
      kind: prefix
      value: apifeatureusage-
    - direction: older
      filtertype: age
      source: creation_date
      unit: days
      unit_count: 2
    options:
      continue_if_exception: false
      delay: 120
      max_num_segments: 1
      timeout_override: null
profile::rsyslog::udp_localhost_compat_port: 11514
