profile::redis::multidc::aof: false
profile::redis::multidc::category: sessions
profile::redis::multidc::discovery: false
profile::redis::multidc::settings:
  auto_aof_rewrite_min_size: 512mb
  bind: 0.0.0.0
  client_output_buffer_limit: slave 512mb 200mb 60
  dir: /srv/redis
  maxmemory: 500Mb
  maxmemory_policy: volatile-lru
  maxmemory_samples: 5
  no_appendfsync_on_rewrite: true
  save: 300 100
  slave_read_only: false
  stop_writes_on_bgsave_error: false
profile::redis::multidc::version_override: null
