aptly::manage_nginx: false
profile::ci::slave::labs::common::manage_srv: false
profile::java::java_packages:
- variant: jre-headless
  version: '11'
profile::mediawiki::mcrouter_wancache::use_onhost_memcached: false
