profile::docker::engine::declare_service: true
profile::docker::engine::settings: {}
profile::docker::engine::version: 1.12.6-0~debian-jessie
profile::docker::runner::service_defs:
  eventgate-main:
    config:
      logging:
        level: info
        streams:
        - type: stdout
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
      metrics:
        port: 9092
        type: prometheus
      num_workers: 0
      services:
      - conf:
          client_ip_connection_limit: 10
          cors: '*'
          csp: default-src 'none'; script-src 'self' 'unsafe-inline'; connect-src
            *; style-src 'self' 'unsafe-inline'; img-src 'self'; font-src 'self'
          kafka:
            conf:
              metadata.broker.list: deployment-kafka-main-1.deployment-prep.eqiad.wmflabs:9092,deployment-kafka-main-2.deployment-prep.eqiad.wmflabs:9092
              statistics.interval.ms: 10000
          port: 8092
          spec: ./spec.yaml
          streams:
            page-create:
              description: 'Mediawiki Page create events. This page create stream
                is just the first revision create

                event for each page. As such, it reuses the mediawiki/revision/create
                schema.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/blob/master/jsonschema/mediawiki/revision/create'
              topics:
              - eqiad.mediawiki.page-create
              - codfw.mediawiki.page-create
            page-delete:
              description: 'Mediawiki Page delete events.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/blob/master/jsonschema/mediawiki/page/delete'
              topics:
              - eqiad.mediawiki.page-delete
              - codfw.mediawiki.page-delete
            page-links-change:
              description: 'Mediawiki Page Links change events.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/blob/master/jsonschema/mediawiki/page/links-change'
              topics:
              - eqiad.mediawiki.page-links-change
              - codfw.mediawiki.page-links-change
            page-move:
              description: 'Mediawiki Page move (rename) events.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/blob/master/jsonschema/mediawiki/page/move'
              topics:
              - eqiad.mediawiki.page-move
              - codfw.mediawiki.page-move
            page-properties-change:
              description: 'Mediawiki Page Properties change events.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/blob/master/jsonschema/mediawiki/page/properties-change'
              topics:
              - eqiad.mediawiki.page-properties-change
              - codfw.mediawiki.page-properties-change
            page-undelete:
              description: 'Mediawiki Page un-delete events.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/blob/master/jsonschema/mediawiki/page/undelete'
              topics:
              - eqiad.mediawiki.page-undelete
              - codfw.mediawiki.page-undelete
            recentchange:
              description: 'Mediawiki RecentChanges feed.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/tree/master/jsonschema/mediawiki/recentchange'
              topics:
              - eqiad.mediawiki.recentchange
              - codfw.mediawiki.recentchange
            revision-create:
              description: 'Mediawiki Revision create events.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/tree/master/jsonschema/mediawiki/revision/create'
              topics:
              - eqiad.mediawiki.revision-create
              - codfw.mediawiki.revision-create
            revision-score:
              description: 'Mediawiki Revision Score feed. Every new revision in an
                ORES enabled wiki should have a

                revision-score event. This schema is structured differnetly than ORES
                API results, as

                event schemas should map well into RDBMS / SQL environments where
                columns must be

                strongly typed.

                NOTE: Only the most commonly used ORES model scores are included in
                each event

                (the ones returned by https://ores.wikimedia.org/v3/precache).

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/tree/master/jsonschema/mediawiki/revision/score'
              topics:
              - eqiad.mediawiki.revision-score
              - codfw.mediawiki.revision-score
            test:
              description: 'A test event stream. A new event is posted about once
                a minute.

                Schema: https://github.com/wikimedia/mediawiki-event-schemas/tree/master/jsonschema/test/event'
              topics:
              - eqiad.test.event
              - codfw.test.event
          user_agent: eventstreams-beta
        module: app.js
        name: eventgate-main
      worker_heap_limit_mb: 250
    image_name: mediawiki-services-eventstreams
    namespace: wikimedia
    port: 8092
    version: 2019-12-19-161005-production
puppetmaster: deployment-puppetmaster03.deployment-prep.eqiad.wmflabs
