cluster: parsoid
has_lvs: false
profile::envoy::ensure: present
profile::mediawiki::apc_shm_size: 128M
profile::mediawiki::httpd::logrotate_retention: 12
profile::mediawiki::mcrouter_wancache::num_proxies: 5
profile::mediawiki::php::enable_fpm: true
profile::mediawiki::php::fpm_config:
  apc.ttl: 10
  opcache.interned_strings_buffer: 96
  opcache.memory_consumption: 1024
profile::mediawiki::php::php_version: '7.4'
profile::mediawiki::php::request_timeout: 201
profile::mediawiki::php::restarts::ensure: present
profile::mediawiki::php::restarts::has_lvs: false
profile::mediawiki::php::restarts::opcache_limit: 200
profile::mediawiki::vhost_feature_flags: {}
profile::mediawiki::webserver::has_tls: true
profile::services_proxy::envoy::ensure: absent
profile::tlsproxy::envoy::access_log: true
profile::tlsproxy::envoy::capitalize_headers: true
profile::tlsproxy::envoy::ensure: present
profile::tlsproxy::envoy::global_cert_name: parsoid.svc.deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::retries: false
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 443
profile::tlsproxy::envoy::upstream_response_timeout: 203.0
