authdns_servers:
  cloudservices1003.wikimedia.org: 208.80.154.135
  cloudservices1004.wikimedia.org: 208.80.154.11
http_proxy: ''
profile::acme_chief::accounts:
  0f076461095e47a9dce5334db021a891:
    directory: https://acme-v02.api.letsencrypt.org/directory
    regr: '{"body": {}, "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/53552803"}'
profile::acme_chief::active: deployment-acme-chief03.deployment-prep.eqiad.wmflabs
profile::acme_chief::certificates:
  mx:
    CN: mail.beta.wmflabs.org
    SNI:
    - mail.beta.wmflabs.org
    authorized_regexes:
    - deployment-mx02\.deployment-prep\.eqiad\.wmflabs
    challenge: dns-01
  unified:
    CN: '*.wikimedia.beta.wmflabs.org'
    SNI:
    - beta.wmflabs.org
    - upload.beta.wmflabs.org
    - m.wikidata.beta.wmflabs.org
    - wikidata.beta.wmflabs.org
    - '*.wikibooks.beta.wmflabs.org'
    - '*.wikimedia.beta.wmflabs.org'
    - '*.wikinews.beta.wmflabs.org'
    - '*.wikipedia.beta.wmflabs.org'
    - '*.wikiquote.beta.wmflabs.org'
    - '*.wikisource.beta.wmflabs.org'
    - '*.wikiversity.beta.wmflabs.org'
    - '*.wikivoyage.beta.wmflabs.org'
    - '*.wiktionary.beta.wmflabs.org'
    - '*.m.wikibooks.beta.wmflabs.org'
    - '*.m.wikimedia.beta.wmflabs.org'
    - '*.m.wikinews.beta.wmflabs.org'
    - '*.m.wikipedia.beta.wmflabs.org'
    - '*.m.wikiquote.beta.wmflabs.org'
    - '*.m.wikisource.beta.wmflabs.org'
    - '*.m.wikiversity.beta.wmflabs.org'
    - '*.m.wikivoyage.beta.wmflabs.org'
    - '*.m.wiktionary.beta.wmflabs.org'
    - '*.zero.wikipedia.beta.wmflabs.org'
    authorized_regexes:
    - ^deployment-cache-(text0[56]|upload0[56])\.deployment-prep\.eqiad\.wmflabs$
    challenge: dns-01
  wikibase:
    CN: wikiba-se.beta.wmflabs.org
    SNI:
    - wikiba-se.beta.wmflabs.org
    authorized_regexes:
    - deployment-cache-text05\.deployment-prep\.eqiad\.wmflabs
    challenge: dns-01
profile::acme_chief::challenges:
  dns-01:
    issuing_ca: letsencrypt.org
    ns_records:
    - cloud-ns0.wikimedia.org.
    - cloud-ns1.wikimedia.org.
    resolver_port: 53
    zone_update_cmd: /usr/local/bin/acme-chief-designate-sync.py
profile::acme_chief::cloud::designate_sync_auth_url: http://cloudcontrol1003.wikimedia.org:5000/v3
profile::acme_chief::cloud::designate_sync_project_name: deployment-prep
profile::acme_chief::cloud::designate_sync_region_name: eqiad1-r
profile::acme_chief::cloud::designate_sync_tidyup_enabled: true
profile::acme_chief::cloud::designate_sync_username: deployment-prep-dns-manager
profile::acme_chief::passive: deployment-acme-chief04.deployment-prep.eqiad.wmflabs
