profile::etcd::v3::adv_client_port: 2379
profile::etcd::v3::allow_from: 0.0.0.0
profile::etcd::v3::cluster_bootstrap: true
profile::etcd::v3::cluster_name: beta
profile::etcd::v3::discovery: name=http://deployment-etcd02.deployment-prep.eqiad1.wikimedia.cloud:2380
profile::etcd::v3::max_latency: 1
profile::etcd::v3::use_client_certs: false
