profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 20.10.5+dfsg1-1
profile::docker::runner::service_defs: {}
profile::docker::storage::physical_volumes: /dev/md1
profile::docker::storage::vg_to_remove: todelete
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
