profile::docker::engine::declare_service: true
profile::docker::engine::settings: {}
profile::docker::runner::service_defs:
  mediawiki-services-citoid:
    config:
      logging:
        level: trace
      metrics: {}
      num_workers: 0
      services:
      - conf:
          allowPrivateAddresses: false
          cors: '*'
          mailto: services@lists.wikimedia.org
          maxRedirects: 10
          port: 1970
          proxy: null
          pubmed: false
          userAgent: Citoid (Wikimedia tool; learn more at https://www.mediawiki.org/wiki/Citoid)
          wskey: ''
          xisbn: false
          zotero: false
          zoteroInterface: deployment-docker-citoid01.deployment-prep.eqiad.wmflabs
          zoteroPort: 1969
          zoteroUseProxy: false
        module: ./app.js
        name: citoid
      worker_heap_limit_mb: 250
    namespace: wikimedia
    override_cmd: -c /etc/mediawiki-services-citoid/config.yaml
    port: 1970
    version: 2019-04-01-104952-production
  mediawiki-services-zotero:
    namespace: wikimedia
    port: 1969
    version: 2019-02-01-074657-candidate
