profile::envoy::ensure: present
profile::services_proxy::envoy::ensure: absent
profile::swift::cluster_label: deployment-prep
profile::swift::global_account_keys:
  deployment-prep: {}
profile::tlsproxy::envoy::cfssl_options:
  hosts:
  - ms-fe.svc.deployment-prep.eqiad1.wikimedia.cloud
  - upload.wikimedia.beta.wmflabs.org
  - upload.beta.wmflabs.org
profile::tlsproxy::envoy::global_cert_name: ms-fe.svc.deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 443
