profile::envoy::ensure: present
profile::services_proxy::envoy::ensure: absent
profile::tlsproxy::envoy::cfssl_label: deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::global_cert_name: ms-fe.svc.deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 444
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
