profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 18.09.1+dfsg1-7.1+deb10u1
profile::docker::runner::service_defs:
  mediawiki-services-mobileapps:
    config:
      logging:
        level: trace
    namespace: wikimedia
    port: 8888
    version: 2020-07-14-184348-production
