profile::conftool::master::sync_dir: /etc/conftool/data-local
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
role::puppetmaster::standalone::puppetdb_host:
- deployment-puppetdb03.deployment-prep.eqiad.wmflabs
role::puppetmaster::standalone::storeconfigs: puppetdb
