profile::envoy::ensure: present
profile::lvs::realserver::pools:
  swift:
    services:
    - dummy
profile::services_proxy::envoy::ensure: absent
profile::swift::cluster_label: deployment-prep
profile::tlsproxy::envoy::cfssl_options:
  hosts:
  - ms-fe.svc.deployment-prep.eqiad1.wikimedia.cloud
  - upload.wikimedia.beta.wmcloud.org
  - upload.wikimedia.beta.wmflabs.org
profile::tlsproxy::envoy::global_cert_name: ms-fe.svc.deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 443
service::catalog:
  swift:
    aliases:
    - ms-fe
    description: dummy to make puppet happy
    encryption: false
    ip:
      eqiad:
        default: 127.0.0.1
    lvs:
      class: low-traffic
      conftool:
        cluster: swift
        service: swift-fe
      depool_threshold: 0.5
      enabled: true
      monitors:
        IdleConnection:
          max-delay: 300
          timeout-clean-reconnect: 3
        ProxyFetch:
          url:
          - http://localhost/monitoring/frontend
      scheduler: wrr
    port: 80
    sites:
    - eqiad
    state: production
