profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 18.09.1+dfsg1-7.1+deb10u1
profile::docker::runner::service_defs:
  mediawiki-services-push-notifications:
    config:
      logging:
        level: trace
      num_workers: 0
      services:
      - conf:
          apns:
            cert: /etc/mediawiki-services-push-notifications/apns-push-toolforge.p12
            production: true
          port: 8900
          spec: ./spec.yaml
          user_agent: push-notifications (beta)
        module: ./dist/app.js
        name: push-notifications
    namespace: wikimedia
    override_cmd: -c /etc/mediawiki-services-push-notifications/config.yaml
    port: 8900
    version: 2020-06-15-112756-publish
