cluster: redis
profile::redis::multidc::aof: true
profile::redis::multidc::category: jobqueue
profile::redis::multidc::discovery: false
profile::redis::multidc::settings:
  appendonly: true
  auto_aof_rewrite_min_size: 512mb
  bind: 0.0.0.0
  client_output_buffer_limit: slave 2048mb 512mb 60
  dir: /srv/redis
  maxmemory: 8Gb
  no_appendfsync_on_rewrite: true
  save: '""'
  slave_read_only: false
  stop_writes_on_bgsave_error: false
