profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 18.09.1+dfsg1-7.1+deb10u2
profile::docker::runner::service_defs:
  api-gateway:
    config: {}
    image_name: envoy-future
    namespace: wikimedia
    override_cmd: /usr/bin/envoy -c /etc/api-gateway/config.yaml -l debug
    port: 8087
    version: 1.18.3-1
    volume: true
