profile::cassandra::instances:
  deployment-echostore02.deployment-prep.eqiad1.wikimedia.cloud: {}
profile::cassandra::rack: rack1
profile::cassandra::settings:
  cluster_name: echostore-beta
  default_instance_params:
    rpc_address: '%{::ipaddress}'
  listen_address: '%{::ipaddress}'
  logstash_host: deployment-logstash03.deployment-prep.eqiad.wmflabs
  target_version: 3.x
profile::docker::engine::declare_service: true
profile::docker::engine::settings: {}
profile::docker::engine::version: 1.12.6-0~debian-jessie
profile::docker::runner::service_defs:
  mediawiki-services-kask:
    config:
      base_uri: /echoseen/v1
      cassandra:
        authentication:
          password: cassandra
          username: cassandra
        hosts:
        - deployment-echostore02.deployment-prep.eqiad1.wikimedia.cloud
        keyspace: echoseen
        table: values
      default_ttl: 31536000
      listen_address: 0.0.0.0
      listen_port: 8080
      openapi_spec: /go/src/gerrit.wikimedia.org/r/mediawiki/services/kask/openapi.yaml
      service_name: sessions
    namespace: wikimedia
    override_cmd: ./kask --config /etc/mediawiki-services-kask/config.yaml
    port: 8080
    version: v1.0.10
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
