profile::graphite::base::cluster_servers:
- deployment-graphite01.deployment-prep.eqiad1.wikimedia.cloud
profile::graphite::base::cors_origins:
- https?://grafana-cloud.wikimedia.org
- https?://grafana-labs.wikimedia.org
profile::graphite::base::forward_clusters:
  big_users:
  - deployment-graphite01.deployment-prep.eqiad1.wikimedia.cloud:1903
  default:
  - deployment-graphite01.deployment-prep.eqiad1.wikimedia.cloud:1903
profile::graphite::base::uwsgi_processes: 4
profile::graphite::production::hostname: graphite.wikimedia.beta.wmflabs.org
profile::graphite::production::use_cas: false
profile::netconsole::client::ensure: absent
profile::tlsproxy::envoy::access_log: true
profile::tlsproxy::envoy::capitalize_headers: true
profile::tlsproxy::envoy::cfssl_label: deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::cfssl_options:
  hosts:
  - statsd.svc.deployment-prep.eqiad1.wikimedia.cloud
  - graphite.wikimedia.beta.wmflabs.org
  - '%{facts.networking.fqdn}'
profile::tlsproxy::envoy::ensure: present
profile::tlsproxy::envoy::global_cert_name: statsd.svc.deployment-prep.eqiad1.wikimedia.cloud
profile::tlsproxy::envoy::retries: false
profile::tlsproxy::envoy::services:
- port: 80
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 443
profile::tlsproxy::envoy::upstream_response_timeout: 203.0
