profile::docker::engine::declare_service: true
profile::docker::runner::service_defs: "mediawiki-services-wikifeeds:\n  config:\n\
  \    logging:\n      level: trace\n    metrics: {}\n    num_workers: 0\n    services:\n\
  \    - conf:\n        cors: '*'\n        mw_req:\n          headers:\n         \
  \   accept-language: '{{accept-language}}'\n            user-agent: '{{user-agent}}'\n\
  \          method: get\n          query:\n            title: '{{request.params.title}}'\n\
  \          uri: http://appservers.svc.deployment-prep.eqiad1.wikimedia.cloud/w/index.php\n\
  \        mwapi_req:\n          body: '{{ default(request.query, {}) }}'\n      \
  \    headers:\n            accept-language: '{{accept-language}}'\n            host:\
  \ '{{request.params.domain}}'\n            user-agent: '{{user-agent}}'\n      \
  \    method: post\n          uri: http://appservers.svc.deployment-prep.eqiad1.wikimedia.cloud/w/api.php\n\
  \        port: 8889\n        restbase_req:\n          body: '{{request.body}}'\n\
  \          headers: '{{request.headers}}'\n          method: '{{request.method}}'\n\
  \          query: '{{ default(request.query, {}) }}'\n          uri: http://deployment-restbase05.deployment-prep.eqiad1.wikimedia.cloud:7231/{{domain}}/v1/{+path}\n\
  \        user_agent: WMF Wikifeeds beta\n      module: ./app.js\n      name: wikifeeds\n\
  \  namespace: wikimedia\n  override_cmd: -c /etc/mediawiki-services-wikifeeds/config.yaml\n\
  \  port: 8889\n  version: 2023-11-28-215911-production\n"
