profile::trafficserver::tls::available_unified_certs:
  lets-encrypt:
    acme_chief: true
    cert_files:
    - acmecerts/unified/live/rsa-2048.chained.crt
    - acmecerts/unified/live/ec-prime256v1.chained.crt
    default: true
    private_key_files:
    - acmecerts/unified/live/rsa-2048.key
    - acmecerts/unified/live/ec-prime256v1.key
profile::trafficserver::tls::parent_rules:
- dest_domain: .
  parent:
  - 127.0.0.2:3120
  - 127.0.0.3:3121
  - 127.0.0.4:3122
  - 127.0.0.5:3123
  - 127.0.0.6:3124
  - 127.0.0.7:3125
  - 127.0.0.8:3126
  - 127.0.0.9:3127
  parent_is_proxy: 'false'
  round_robin: strict
profile::trafficserver::tls::unified_acme_chief: true
public_tls_unified_cert_vendor: lets-encrypt
