profile::hcaptcha::hcaptcha_secret: s3cr3t
profile::hcaptcha::hcaptcha_sitekey: somesitekey
profile::hcaptcha::proxy::ip_hash_salt: nomnomnom
profile::hcaptcha::proxy::nginx_ipblinding_conf: ''
profile::hcaptcha::proxy::nginx_private_conf: proxy_set_header X-Clacks-Overhead "GNU
  Terry Pratchett";
profile::hcaptcha::proxy::wikimedia_domains: '%{alias(''wikimedia_domains'')}'
profile::lvs::realserver::pools:
  proxoid:
    services:
    - nginx
profile::nginx::managed: false
profile::nginx::modules:
- lua
profile::nginx::variant: extras
proxoid:
  description: dummy config to ensure clean puppet run
  discovery:
  - active_active: true
    dnsdisc: proxoid
  encryption: true
  ip:
    eqiad:
      default: 127.0.0.1
  lvs:
    class: low-traffic
    conftool:
      cluster: proxoid
      service: nginx
    depool_threshold: 0.5
    enabled: true
    monitors:
      IdleConnection:
        max-delay: 300
        timeout-clean-reconnect: 3
      ProxyFetch:
        url:
        - http://localhost/healthz
    scheduler: mh
    scheduler_flag: mh-port
  page: false
  port: 4260
  probes:
  - path: /healthz
    type: http
  sites:
  - eqiad
  state: production
