cache::alternate_domains: {}
cache::cluster: text
cache::lua_support: true
cache::text::nodes:
  eqiad:
  - deployment-cache-text06.deployment-prep.eqiad.wmflabs
cluster: cache_text
nginx::variant: extras
profile::cache::base::varnish_version: 5
profile::cache::ssl::unified::acme_chief: true
profile::cache::ssl::unified::certs: []
profile::cache::ssl::unified::certs_active: []
profile::cache::ssl::unified::letsencrypt: false
profile::cache::ssl::wikibase::acme_chief: true
profile::cache::ssl::wikibase::letsencrypt: false
profile::cache::ssl::wikibase::monitoring: false
profile::cache::varnish::common_vcl_config:
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  maps_domain: maps.beta.wmflabs.org
  purge_host_regex: ^(?!(upload|maps)\.beta\.wmflabs\.org)
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
profile::cache::varnish::separate_vcl:
- misc
profile::tlsproxy::instance::nginx_variant: extras
profile::trafficserver::backend::mapping_rules:
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="2F"'
  - '@pparam="21 24 26 27 28 29 2A 2B 2C 3A 3B 3D 40 5B 5D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/x-mediawiki-original.lua'
  replacement: http://deployment-ms-fe03.deployment-prep.eqiad.wmflabs
  target: http://upload.beta.wmflabs.org
  type: map
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="3A 2F 40 21 24 28 29 2A 2C 3B"'
  - '@pparam="5B 5D 26 27 2B 3D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/rb-mw-mangling.lua'
  replacement: http://deployment-mediawiki-07.deployment-prep.eqiad.wmflabs
  target: /
  type: map
- params:
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/normalize-path.lua'
  - '@pparam="3A 40 21 24 28 29 2A 2C 3B 27"'
  - '@pparam="5B 5D 26 2B 3D"'
  - '@plugin=/usr/lib/trafficserver/modules/tslua.so'
  - '@pparam=/etc/trafficserver/lua/rb-mw-mangling.lua'
  - '@plugin=/usr/lib/trafficserver/modules/conf_remap.so'
  - '@pparam=proxy.config.http.server_session_sharing.match=2'
  replacement: http://deployment-restbase01.deployment-prep.eqiad.wmflabs:7231/api/rest_v1
  target: http://(.*)/api/rest_v1
  type: regex_map
profile::trafficserver::tls::available_unified_certs:
  lets-encrypt:
    acme_chief: true
    cert_files:
    - acmecerts/unified/live/rsa-2048.chained.crt
    - acmecerts/unified/live/ec-prime256v1.chained.crt
    default: true
    private_key_files:
    - acmecerts/unified/live/rsa-2048.key
    - acmecerts/unified/live/ec-prime256v1.key
profile::trafficserver::tls::inbound_tls_settings:
  common:
    cipher_suite: -ALL:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA
    enable_tlsv1: 0
    enable_tlsv1_1: 0
    enable_tlsv1_2: 1
    enable_tlsv1_3: 0
  dhparams_file: /etc/ssl/dhparam.pem
  do_ocsp: 0
  load_elevated: 1
  max_record_size: 16383
  session_cache: 2
  session_cache_auto_clear: 1
  session_cache_buckets: 256
  session_cache_size: 102400
  session_ticket_enable: 0
  ssl_handshake_timeout_in: 60
profile::trafficserver::tls::parent_rules:
- dest_domain: .
  parent:
  - 127.0.0.2:3120
  - 127.0.0.3:3121
  - 127.0.0.4:3122
  - 127.0.0.5:3123
  - 127.0.0.6:3124
  - 127.0.0.7:3125
  - 127.0.0.8:3126
  - 127.0.0.9:3127
  parent_is_proxy: 'false'
  round_robin: strict
profile::trafficserver::tls::unified_acme_chief: true
public_tls_unified_cert_vendor: lets-encrypt
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
