profile::base::overlayfs: true
profile::base::production::role_description: cirrussearch
profile::opensearch::base_data_dir: /srv/opensearch
profile::opensearch::cirrus::bind_mounts:
  /srv/opensearch: /usr/share/opensearch/data
profile::opensearch::cirrus::enable_remote_search: true
profile::opensearch::cirrus::expose_http: false
profile::opensearch::cirrus::ferm_srange: ''
profile::opensearch::cirrus::oci_image::name: opensearch
profile::opensearch::cirrus::oci_image::ns: repos/data-engineering
profile::opensearch::cirrus::oci_image::version: 2026-05-13-143357-2b2e022d3e2756b0dbd31d66e341a587f5d3b8d7-production2
profile::opensearch::cirrus::ssl_provider: cfssl
profile::opensearch::cirrus::storage_device: sda
profile::opensearch::common_settings:
  auto_create_index: +apifeatureusage-*,-*
  awareness_attributes: ''
  bulk_thread_pool_executors: 5
  certificate_name: '%{::fqdn}'
  heap_memory: 4g
  ltr_cache_size: 100mb
  reindex_remote_whitelist: ''
  search_shard_count_limit: 1000
profile::opensearch::config_version: '1'
profile::opensearch::dc_settings: {}
profile::opensearch::native_lib_path: /usr/share/opensearch/plugins/opensearch-knn/lib
profile::opensearch::rack: ''
profile::opensearch::row: ''
profile::tlsproxy::envoy::cfssl_options:
  hosts:
  - '%{facts.networking.fqdn}'
profile::tlsproxy::envoy::global_cert_name: '%{facts.networking.fqdn}'
profile::tlsproxy::envoy::services:
- port: 9200
  server_names:
  - '*'
profile::tlsproxy::envoy::sni_support: 'no'
profile::tlsproxy::envoy::ssl_provider: cfssl
profile::tlsproxy::envoy::tls_port: 9243
puppetmaster: deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
puppetserver: deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
