profile::cassandra::instances:
  deployment-echostore02.deployment-prep.eqiad1.wikimedia.cloud: {}
profile::cassandra::rack: rack1
profile::cassandra::settings:
  cluster_name: sessions-beta
  default_instance_params:
    rpc_address: '%{::ipaddress}'
  listen_address: '%{::ipaddress}'
  logstash_host: deployment-logstash03.deployment-prep.eqiad.wmflabs
  target_version: 4.x
profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 18.09.1+dfsg1-7.1+deb10u3
profile::docker::runner::service_defs:
  mediawiki-services-kask:
    config:
      base_uri: /echoseen/v1
      cassandra:
        authentication:
          password: cassandra
          username: cassandra
        hosts:
        - deployment-echostore02.deployment-prep.eqiad1.wikimedia.cloud
        keyspace: kask
        table: values
      default_ttl: 84000
      listen_address: 0.0.0.0
      listen_port: 8080
      openapi_spec: /go/src/gerrit.wikimedia.org/r/mediawiki/services/kask/openapi.yaml
      service_name: echostore
    namespace: wikimedia
    override_cmd: ./kask --config /etc/mediawiki-services-kask/config.yaml
    port: 8080
    version: v1.0.10
profile::java::java_packages:
- variant: jdk-headless
  version: '8'
- variant: jdk-headless
  version: '11'
puppetmaster: deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
