docker::gvisor::ensure: absent
profile::docker::runner::service_defs:
  thumbor:
    config: {}
    image_name: operations-software-thumbor-plugins
    namespace: wikimedia
    port: 8080
    version: 2023-10-06-153556-production
