profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 20.10.5+dfsg1-1+deb11u2
profile::docker::runner::service_defs:
  changeprop:
    config: {}
    image_name: mediawiki-services-change-propagation
    namespace: wikimedia
    override_cmd: /srv/service/server.js -c /etc/changeprop/config.yaml
    port: 7272
    version: 2023-11-20-162131-production
    volume: true
  cpjobqueue:
    config: {}
    image_name: mediawiki-services-change-propagation
    namespace: wikimedia
    override_cmd: /srv/service/server.js -c /etc/cpjobqueue/config.yaml
    port: 7272
    version: 2023-11-20-162131-production
    volume: true
