profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 18.09.1+dfsg1-7.1+deb10u2
profile::docker::runner::service_defs:
  mediawiki-services-mobileapps:
    config:
      logging:
        level: trace
        name: mobileapps
        streams:
        - named_levels: true
          type: stdout
      metrics: {}
      num_workers: ncpu * 1.5
      services:
      - conf:
          corepagehtml_req:
            headers:
              accept-language: '{{accept-language}}'
              host: '{{request.params.domain}}'
            method: GET
            uri: https://deployment-mediawiki14.deployment-prep.eqiad1.wikimedia.cloud/w/rest.php/v1/page/{{title}}/with_html
          corerevisionhtml_req:
            headers:
              accept-language: '{{accept-language}}'
              host: '{{request.params.domain}}'
            method: GET
            uri: https://deployment-mediawiki14.deployment-prep.eqiad1.wikimedia.cloud/w/rest.php/v1/revision/{{revision}}/with_html
          cors: '*'
          mobile_html_csp: 'default-src ''none''; connect-src app://*.wikipedia.org
            https://*.wikipedia.org; media-src app://upload.wikimedia.org https://upload.wikimedia.org
            ''self''; img-src app://*.wikimedia.org https://*.wikimedia.org app://wikimedia.org
            https://wikimedia.org ''self'' data:; object-src ''none''; script-src
            app://meta.wikimedia.org https://meta.wikimedia.org ''unsafe-inline'';
            style-src app://meta.wikimedia.org https://meta.wikimedia.org app://*.wikipedia.org
            https://*.wikipedia.org ''self'' ''unsafe-inline''; frame-ancestors ''self'' '
          mobile_html_local_rest_api_base_uri_template: //{{domain}}/api/rest_v1/
          mobile_html_rest_api_base_uri: //meta.wikimedia.org/api/rest_v1/
          mobile_view_languages:
          - zh
          - kk
          mw_resource_loader_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              host: '{{request.params.domain}}'
              user-agent: '{{user-agent}}'
            method: post
            uri: https://deployment-mediawiki14.deployment-prep.eqiad1.wikimedia.cloud/w/load.php
          mwapi_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              accept-language: '{{accept-language}}'
              content-type: application/x-www-form-urlencoded
              host: '{{request.params.domain}}'
              user-agent: '{{user-agent}}'
            method: post
            uri: https://deployment-mediawiki14.deployment-prep.eqiad1.wikimedia.cloud/w/api.php
          pcs_handles_redirects: false
          port: 8888
          restbase_compatibility:
            security_headers: false
          restbase_req:
            body: '{{request.body}}'
            headers: '{{request.headers}}'
            method: '{{request.method}}'
            query: '{{ default(request.query, {}) }}'
            timeout: 60000
            uri: http://deployment-restbase05.deployment-prep.eqiad1.wikimedia.cloud:7231/{{domain}}/v1/{+path}
          restrict_domains: false
          use_coreparsoid_endpoint: true
          user_agent: Mobile-Content-Service/WMF
        module: ./app.js
        name: mobileapps
      startup_concurrency: 4
      worker_heap_limit_mb: 750
      worker_heartbeat_timeout: 15000
    environment:
      NODE_ENV: beta
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    namespace: wikimedia
    override_cmd: -c /etc/mediawiki-services-mobileapps/config.yaml
    port: 8888
    version: 2025-08-14-121918-production
