definitions:
- 2020-01-07-204419-production
profile::docker::engine::declare_service: true
profile::docker::engine::settings: {}
profile::docker::engine::version: 1.12.6-0~debian-jessie
profile::docker::runner::service_defs:
  eventgate-analytics:
    config:
      logging:
        level: info
        streams:
        - type: stdout
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
      metrics:
        host: cloudmetrics1002.eqiad.wmnet
        name: eventgate-analytics
        port: 8125
        type: statsd
      num_workers: 0
      services:
      - conf:
          allow_absolute_schema_uris: false
          csp: false
          error_stream: eventgate-analytics.error.validation
          eventgate_factory_module: /srv/service/eventgate-wikimedia.js
          id_field: meta.id
          kafka:
            conf:
              metadata.broker.list: deployment-kafka-jumbo-1.deployment-prep.eqiad.wmflabs:9092,deployment-kafka-jumbo-2.deployment-prep.eqiad.wmflabs:9092
              statistics.interval.ms: 10000
            topic_conf: {}
          port: 8192
          schema_base_uris:
          - file:///srv/service/schemas/event/primary/jsonschema/
          - file:///srv/service/schemas/event/secondary/jsonschema/
          - http://schema-beta.wmflabs.org/repositories/secondary/jsonschema/
          schema_precache_uris:
          - /error/0.0.3
          - /test/event/0.0.2
          - /mediawiki/api/request/0.0.1
          - /mediawiki/cirrussearch/request/0.0.1
          schema_uri_field: $schema
          stream_field: meta.stream
          topic_prefix: eqiad.
          user_agent: eventgate-analytics
        entrypoint: app
        module: eventgate
        name: eventgate-analytics
      worker_heap_limit_mb: 250
    image_name: eventgate-wikimedia
    namespace: wikimedia
    override_cmd: /srv/service/node_modules/.bin/eventgate -c /etc/eventgate-analytics/config.yaml
    port: 8192
    version: 2020-02-25-183224-production
  eventgate-analytics-external:
    config:
      logging:
        level: info
        streams:
        - type: stdout
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
      metrics:
        host: cloudmetrics1002.eqiad.wmnet
        name: eventgate-analytics-external
        port: 8125
        type: statsd
      num_workers: 0
      services:
      - conf:
          allow_absolute_schema_uris: false
          csp: false
          error_stream: eventgate-analytics-external.error.validation
          eventgate_factory_module: /srv/service/eventgate-wikimedia.js
          id_field: meta.id
          kafka:
            conf:
              metadata.broker.list: deployment-kafka-jumbo-1.deployment-prep.eqiad.wmflabs:9092,deployment-kafka-jumbo-2.deployment-prep.eqiad.wmflabs:9092
              statistics.interval.ms: 10000
            topic_conf: {}
          port: 8492
          schema_base_uris:
          - file:///srv/service/schemas/event/primary/jsonschema/
          - file:///srv/service/schemas/event/secondary/jsonschema/
          - http://schema-beta.wmflabs.org/repositories/secondary/jsonschema/
          schema_precache_uris:
          - /error/0.0.3
          - /test/event/1.0.0
          schema_uri_field: $schema
          stream_config_is_dynamic: true
          stream_config_object_path: streams
          stream_config_precache_list:
          - test.event
          stream_config_recache_on_expire: true
          stream_config_ttl: 60
          stream_config_uri: https://deployment.wikimedia.beta.wmflabs.org/w/api.php?action=streamconfigs&format=json&all_settings&streams=<%=
            stream %>
          stream_field: meta.stream
          topic_prefix: eqiad.
          user_agent: eventgate-analytics-external
        entrypoint: app
        module: eventgate
        name: eventgate-analytics-external
      worker_heap_limit_mb: 250
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
    image_name: eventgate-wikimedia
    namespace: wikimedia
    override_cmd: /srv/service/node_modules/.bin/eventgate -c /etc/eventgate-analytics-external/config.yaml
    port: 8492
    version: 2020-02-25-183224-production
  eventgate-logging:
    config:
      logging:
        level: info
        name: eventgate-logging
        streams:
        - type: stdout
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
      metrics:
        host: cloudmetrics1002.eqiad.wmnet
        name: eventgate-logging
        port: 8125
        type: statsd
      num_workers: 0
      services:
      - conf:
          allow_absolute_schema_uris: true
          csp: false
          error_stream: eventgate-logging.error.validation
          eventgate_factory_module: ../lib/factories/wikimedia-eventgate
          id_field: meta.id
          kafka:
            conf:
              metadata.broker.list: deployment-logstash03.deployment-prep.eqiad.wmflabs:9092
              statistics.interval.ms: 10000
            topic_conf: {}
          port: 8992
          schema_base_uris:
          - file:///srv/service/schemas/event/primary/jsonschema/
          schema_precache_uris:
          - /mediawiki/client/error/1.0.0
          schema_uri_field: $schema
          stream_field: meta.stream
          topic_prefix: eqiad.
          user_agent: eventgate-logging
        entrypoint: app
        module: eventgate
      worker_heap_limit_mb: 250
    image_name: eventgate-wikimedia
    namespace: wikimedia
    override_cmd: /srv/service/node_modules/.bin/eventgate -c /etc/eventgate-logging/config.yaml
    port: 8992
    version: 2020-02-25-183224-production
  eventgate-main:
    config:
      logging:
        level: info
        streams:
        - type: stdout
        - host: deployment-logstash03.deployment-prep.eqiad.wmflabs
          port: 12201
          type: gelf
      metrics:
        host: cloudmetrics1002.eqiad.wmnet
        name: eventgate-main
        port: 8125
        type: statsd
      num_workers: 0
      services:
      - conf:
          allow_absolute_schema_uris: false
          csp: false
          error_stream: eventgate-main.error.validation
          eventgate_factory_module: ../lib/factories/wikimedia-eventgate
          id_field: meta.id
          kafka:
            conf:
              metadata.broker.list: deployment-kafka-main-1.deployment-prep.eqiad.wmflabs:9092,deployment-kafka-main-2.deployment-prep.eqiad.wmflabs:9092
              statistics.interval.ms: 10000
            topic_conf: {}
          port: 8292
          schema_base_uris:
          - file:///srv/service/schemas/event/primary/jsonschema/
          schema_precache_uris:
          - /error/0.0.3
          - /test/event/0.0.3
          - /change-prop/retry/1.0.0
          - /change-prop/continue/1.0.0
          - /resource_change/1.0.0
          - /mediawiki/page/move/1.0.0
          - /mediawiki/page/restrictions-change/1.0.0
          - /mediawiki/page/delete/1.0.0
          - /mediawiki/page/links-change/1.0.0
          - /mediawiki/page/properties-change/1.0.0
          - /mediawiki/page/undelete/1.0.0
          - /mediawiki/recentchange/1.0.0
          - /mediawiki/user/blocks-change/1.0.0
          - /mediawiki/centralnotice/campaign/change/1.0.0
          - /mediawiki/centralnotice/campaign/delete/1.0.0
          - /mediawiki/centralnotice/campaign/create/1.0.0
          - /mediawiki/job/1.0.0
          - /mediawiki/revision/visibility-change/1.0.0
          - /mediawiki/revision/score/2.0.0
          - /mediawiki/revision/tags-change/1.0.0
          - /mediawiki/revision/create/1.0.0
          schema_uri_field: $schema
          stream_field: meta.stream
          topic_prefix: eqiad.
          user_agent: eventgate-main
        entrypoint: app
        module: eventgate
        name: eventgate-main
      worker_heap_limit_mb: 250
    image_name: eventgate-wikimedia
    namespace: wikimedia
    override_cmd: /srv/service/node_modules/.bin/eventgate -c /etc/eventgate-main/config.yaml
    port: 8292
    version: 2020-02-25-183224-production
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
