cache::alternate_domains: {}
cache::cluster: upload
cache::lua_support: true
cache::upload::nodes:
  eqiad:
  - deployment-cache-upload05.deployment-prep.eqiad.wmflabs
nginx::variant: extras
profile::cache::base::varnish_version: 5
profile::cache::ssl::unified::acme_chief: true
profile::cache::ssl::unified::certs: []
profile::cache::ssl::unified::certs_active: []
profile::cache::ssl::unified::letsencrypt: false
profile::cache::varnish::common_vcl_config:
  allowed_methods: ^(GET|HEAD|OPTIONS|POST|PURGE|PUT|DELETE)$
  maps_domain: maps.beta.wmflabs.org
  purge_host_regex: ^(?!(upload|maps)\.beta\.wmflabs\.org)
  shortener_domain: w-beta.wmflabs.org
  static_host: en.wikipedia.beta.wmflabs.org
  top_domain: beta.wmflabs.org
  upload_domain: upload.beta.wmflabs.org
  upload_webp_hits_threshold: 1000
profile::tlsproxy::instance::nginx_variant: extras
profile::trafficserver::tls::available_unified_certs:
  lets-encrypt:
    acme_chief: true
    cert_files:
    - unified/live/rsa-2048.chained.crt
    - unified/live/ec-prime256v1.chained.crt
    default: true
    private_key_files:
    - unified/live/rsa-2048.key
    - unified/live/ec-prime256v1.key
profile::trafficserver::tls::inbound_tls_settings:
  cert_path: /etc/acmecerts/unified/live/
  common:
    cipher_suite: -ALL:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA
    enable_tlsv1: 1
    enable_tlsv1_1: 1
    enable_tlsv1_2: 1
    enable_tlsv1_3: 0
  dhparams_file: /etc/ssl/dhparam.pem
  do_ocsp: 0
  load_elevated: 1
  max_record_size: 16383
  ocsp_stapling_path: /etc/acmecerts/unified/live/
  private_key_path: /etc/acmecerts/unified/live/
  session_cache: 2
  session_cache_auto_clear: 1
  session_cache_buckets: 256
  session_cache_size: 102400
  session_ticket_enable: 0
  ssl_handshake_timeout_in: 60
profile::trafficserver::tls::parent_rules:
- dest_domain: .
  parent:
  - 127.0.0.2:3120
  - 127.0.0.3:3121
  - 127.0.0.4:3122
  - 127.0.0.5:3123
  - 127.0.0.6:3124
  - 127.0.0.7:3125
  - 127.0.0.8:3126
  - 127.0.0.9:3127
  parent_is_proxy: 'false'
  round_robin: strict
profile::trafficserver::tls::unified_acme_chief: true
public_tls_unified_cert_vendor: lets-encrypt
