profile::puppetdb::ca_path: /etc/ssl/certs/Puppet_Internal_CA.pem
profile::puppetdb::database::shared_buffers: 600MB
profile::puppetdb::elk_logging: false
profile::puppetdb::filter_job_id: true
profile::puppetdb::jvm_opts: -Xmx256m
profile::puppetdb::master: deployment-puppetdb03.deployment-prep.eqiad.wmflabs
profile::puppetdb::microservice::allowed_hosts: []
profile::puppetdb::microservice::enabled: false
profile::puppetdb::microservice::port: 8090
profile::puppetdb::microservice::uwsgi_port: 8091
profile::puppetdb::puppetboard_hosts: []
puppetdb_major_version: 4
puppetmaster::servers:
  deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud:
  - loadfactor: 1
    worker: deployment-deployment-puppetserver-1.deployment-prep.eqiad1.wikimedia.cloud
