profile::docker::engine::declare_service: true
profile::docker::engine::packagename: docker.io
profile::docker::engine::settings: {}
profile::docker::engine::version: 20.10.5+dfsg1-1
profile::docker::runner::service_defs:
  function-evaluator-js:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 4
      services:
      - conf:
          port: 6928
        module: ./app.js
        name: function-evaluator-js
      worker_heap_limit_mb: 500
    image_name: wasm-javascript-all
    namespace: repos/abstract-wiki/wikifunctions/function-evaluator
    override_cmd: -c /etc/function-evaluator-js/config.yaml
    port: 6928
    runtime: runsc
    version: latest
  function-evaluator-py:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 4
      services:
      - conf:
          port: 6929
        module: ./app.js
        name: function-evaluator-py
      worker_heap_limit_mb: 500
    image_name: wasm-python3-all
    namespace: repos/abstract-wiki/wikifunctions/function-evaluator
    override_cmd: -c /etc/function-evaluator-py/config.yaml
    port: 6929
    runtime: runsc
    version: latest
  mediawiki-services-function-evaluator:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 7
      services:
      - conf:
          port: 6927
        module: ./app.js
        name: function-evaluator
      worker_heap_limit_mb: 500
    image_name: omnibus
    namespace: repos/abstract-wiki/wikifunctions/function-evaluator
    override_cmd: -c /etc/mediawiki-services-function-evaluator/config.yaml
    port: 6927
    runtime: runsc
    version: latest
  mediawiki-services-function-orchestrator:
    config:
      logging:
        level: trace
        streams:
        - named_levels: true
          type: stdout
      num_workers: 7
      services:
      - conf:
          cors: '*'
          mwapi_req:
            body: '{{ default(request.query, {}) }}'
            headers:
              user-agent: '{{user-agent}}'
            method: post
            uri: https://{{domain}}/w/api.php
          port: 6254
          restbase_req:
            body: '{{request.body}}'
            headers: '{{request.headers}}'
            method: '{{request.method}}'
            query: '{{ default(request.query, {}) }}'
            uri: https://{{domain}}/api/rest_v1/{+path}
          spec: ./spec.yaml
        module: ./app.js
        name: function-orchestrator
      worker_heap_limit_mb: 500
    environment:
      FUNCTION_EVALUATOR_TIMEOUT_MS: '9000'
      NODE_TLS_REJECT_UNAUTHORIZED: '0'
      ORCHESTRATOR_CONFIG: '{ "evaluatorConfigs": [ { "programmingLanguages": ["python-3-9",
        "python-3-8", "python-3-7", "python-3", "python"], "evaluatorUri": "https://wikifunctions-evaluator-beta.wmflabs.org/1/v1/evaluate/",
        "evaluatorWs": "", "useReentrance": false, allowCustomDerializers: true },
        { "programmingLanguages": ["javascript-es2020", "javascript-es2019", "javascript-es2018",
        "javascript-es2017", "javascript-es2016", "javascript-es2015", "javascript"],
        "evaluatorUri": "https://wikifunctions-evaluator-beta.wmflabs.org/1/v1/evaluate/",
        "evaluatorWs": "", "useReentrance": false, allowCustomDerializers: true }
        ] }'
      ORCHESTRATOR_CONFIG_NEW: '{ "evaluatorConfigs": [ { "programmingLanguages":
        ["python-3-9", "python-3-8", "python-3-7", "python-3", "python"], "evaluatorUri":
        "https://wikifunctions-evaluator-python3-beta.wmcloud.org/1/v1/evaluate/",
        "evaluatorWs": "", "useReentrance": false, allowCustomDerializers: true },
        { "programmingLanguages": ["javascript-es2020", "javascript-es2019", "javascript-es2018",
        "javascript-es2017", "javascript-es2016", "javascript-es2015", "javascript"],
        "evaluatorUri": "https://wikifunctions-evaluator-javascript-beta.wmcloud.org/1/v1/evaluate/",
        "evaluatorWs": "", "useReentrance": false, allowCustomDerializers: true }
        ] }'
      ORCHESTRATOR_TIMEOUT_MS: '10000'
      WIKI_API_URL: https://wikifunctions.beta.wmflabs.org/w/api.php
    image_name: function-orchestrator
    namespace: repos/abstract-wiki/wikifunctions
    override_cmd: -c /etc/mediawiki-services-function-orchestrator/config.yaml
    port: 6254
    version: latest
profile::docker::storage::physical_volumes: /dev/md1
profile::docker::storage::vg_to_remove: todelete
puppetmaster: deployment-puppetmaster04.deployment-prep.eqiad.wmflabs
